import test from 'node:test';
import assert from 'node:assert/strict';
import {ContextAgent} from '../server/context-agent/loop.mjs';
import {createSession} from '../server/context-agent/history.mjs';
import {createTools} from '../server/context-agent/tools.mjs';
const call=(name,args,id=name)=>({type:'function_call',name,arguments:typeof args==='string'?args:JSON.stringify(args),call_id:id});
const say=()=>({type:'message',role:'assistant',content:[{type:'output_text',text:'已核对实际工具结果。'}]});
const results=s=>s.records.filter(r=>r.kind==='tool_result').map(r=>({id:r.callId,...JSON.parse(r.output)}));
const setup=()=>{const s=createSession();s.assets.a={id:'a',type:'text',content:'价格18元，背景米白。',ownerId:s.ownerId,version:1};s.assets.b={id:'b',type:'text',content:'容量未知',ownerId:s.ownerId,version:1};return s;};
async function run(s,calls,options={}){let round=0;const agent=new ContextAgent({brain:{respond:async()=>round++===0?calls:[say()]},tools:createTools(),...options});const end=await agent.run(s,'读取来源后修改原稿，只改价格');return {end,round};}
test('independent reads execute in order once and expose complete paired results',async()=>{const s=setup();const {end,round}=await run(s,[call('read_asset',{id:'a'},'one'),call('read_asset',{id:'b'},'two')]);assert.equal(end.status,'completed');assert.equal(round,2);assert.deepEqual(results(s).map(r=>[r.id,r.asset.content]),[['one',s.assets.a.content],['two',s.assets.b.content]]);});
test('read then prewritten edit waits for Agent feedback; original remains intact',async()=>{const s=setup();await run(s,[call('read_asset',{id:'a'}),call('save_document',{parentId:'a',edits:[{before:'18元',after:'20元'}]})]);assert.equal(results(s)[0].ok,true);assert.equal(results(s)[1].status,'not_executed');assert.equal(Object.keys(s.assets).length,2);});
test('independent image and video preparation preserves approval gates without submitting',async()=>{const s=setup();await run(s,[call('generate_image',{prompt:'白瓶',size:'1K'}),call('generate_video',{prompt:'静物',duration:5,ratio:'9:16',resolution:'720p'})],{maxMediaCalls:2});assert.equal(results(s).filter(r=>r.status==='approval_required').length,2);assert.equal(Object.keys(s.invocations).length,0);assert.equal(Object.keys(s.approvals).length,2);});
for(const [label,first]of [['JSON',call('read_asset','{','bad')],['Schema',call('read_asset',{id:123},'bad')],['missing-source',call('read_asset',{id:'absent'},'bad')],['unknown-tool',call('invented',{},'bad')]])test(label+' failure stops subsequent calls with paired feedback',async()=>{const s=setup();await run(s,[first,call('read_asset',{id:'a'},'next')]);const r=results(s);assert.equal(r.length,2);assert.ok(r[0].ok===false||r[0].isError);assert.equal(r[1].status,'not_executed');});
test('two writes execute only first; further mutation waits for actual result',async()=>{const s=setup();await run(s,[call('save_document',{content:'第一份',title:'稿一'},'one'),call('save_document',{content:'第二份',title:'稿二'},'two')]);assert.equal(Object.keys(s.assets).length,3);assert.equal(results(s)[1].status,'not_executed');});
test('cancel during first read closes remaining call IDs without executing them',async()=>{const s=setup(),controller=new AbortController();let executions=0;const tools={definitions:[],execute:async()=>{executions++;controller.abort();return {ok:true};}};const agent=new ContextAgent({brain:{respond:async()=>[call('read_asset',{id:'a'},'one'),call('read_asset',{id:'b'},'two')]},tools});const end=await agent.run(s,'读取',()=>{},controller.signal);assert.equal(end.status,'cancelled');assert.equal(executions,1);assert.equal(results(s).length,2);assert.equal(results(s)[1].code,'cancelled');});
test('question pauses and pairs remaining calls before returning waiting_user',async()=>{const s=setup();const {end}=await run(s,[call('request_user_input',{message:'请选择输出语言',questions:[{key:'language',label:'语言',allowFreeText:true}]}),call('save_document',{content:'不得提前保存'})]);assert.equal(end.status,'waiting_user');assert.equal(results(s).length,2);assert.equal(results(s)[1].status,'not_executed');assert.equal(Object.keys(s.assets).length,2);});
test('deferred edit is rebuilt after read feedback and saved once with the actual parent',async()=>{const s=setup();let step=0;const agent=new ContextAgent({tools:createTools(),brain:{respond:async input=>{if(step++===0)return[call('read_asset',{id:'a'}),call('save_document',{content:'预先编造'},'premature')];if(step===2){assert.equal(results(s)[1].status,'not_executed');return[call('save_document',{parentId:'a',edits:[{before:'18元',after:'20元'}]},'actual')];}return[say()];}}});const end=await agent.run(s,'只把原稿18元改为20元');assert.equal(end.status,'completed');const revisions=Object.values(s.assets).filter(a=>a.parentId==='a');assert.equal(revisions.length,1);assert.equal(revisions[0].content,'价格20元，背景米白。');assert.equal(results(s).length,3);});
