import test from 'node:test';
import assert from 'node:assert/strict';
import {requestAssembly,sessionEvidence} from '../server/debug-session-view.mjs';
import {aggregateRun,stateDiff} from '../server/debug-trace.mjs';
import {groupFlows} from '../dist/debug/focus-view.mjs';
const request=conversation=>({normalizedRequest:{input:[{role:'system',content:'instruction'},{role:'user',content:JSON.stringify({query:'上一轮的回答',conversation})}]}});
test('actual history text is extracted, rather than hidden as unavailable context',()=>{const c=request({recentMessages:[{role:'assistant',content:'我是 deepseek-flash'}],messageIndex:[{messageId:'m'}]});assert.equal(requestAssembly(c).conversation.recentMessages[0].content,'我是 deepseek-flash');assert.equal(requestAssembly(c).source,'actual_request');});
test('repair payload preserves nested original conversation and ordered feedback',()=>{const c={input:[{role:'system',content:'repair'},{role:'user',content:JSON.stringify({original:{conversation:{recentMessages:[{content:'history'}]}},lockedDraft:{}})}]};const a=requestAssembly(c);assert.equal(a.conversation.recentMessages[0].content,'history');assert.equal(a.sequence[0].content,'repair');assert.equal(a.source,'pre_transport');});
test('history includes earlier recorded answers only and never later replies',()=>{const s={turns:[{runId:'a',rawInput:'first'},{runId:'b',rawInput:'current'},{runId:'c',rawInput:'future'}],events:[{runId:'a',type:'final',text:'first reply'},{runId:'c',type:'final',text:'future reply'}]};const e=sessionEvidence(s,1,[],stateDiff);assert.deepEqual(e.history.map(h=>h.content),['first','first reply']);assert.equal(e.globalRounds.length,2);});
test('absent final message is not replaced with latest session messages',()=>{const s={turns:[{runId:'a',rawInput:'first'},{runId:'b',rawInput:'second'}],events:[],messages:[{role:'assistant',content:'later answer'}]};assert.equal(sessionEvidence(s,1,[],stateDiff).history.length,1);});
test('missing global State is unknown, not reconstructed from current ledger',()=>{const s={turns:[{runId:'a'}],events:[],taskStore:{tasks:{later:{status:'COMPLETED'}}}};const e=sessionEvidence(s,0,[],stateDiff);assert.equal(e.currentState.before,null);assert.equal(e.currentState.after,null);assert.deepEqual(e.globalRounds[0].taskSnapshots,[]);});
test('global before/after comparisons use only explicitly recorded snapshots',()=>{const s={turns:[{runId:'a',stateBefore:{data:{activeTaskId:null}},stateAfter:{data:{activeTaskId:'t'}}}],events:[]};assert.equal(sessionEvidence(s,0,[],stateDiff).globalRounds[0].changes[0].new,'t');});
test('message query rejection still exposes history carried in all attempts',()=>{const c=request({recentMessages:[{messageId:'msg_x',role:'assistant',content:'真实上一轮回答'}]});const s={id:'s',turns:[{runId:'r',rawInput:'你上一轮的回答是什么',status:'failed'}],events:[],modelCalls:[{id:'m',runId:'r',...c,validations:[{phase:'understand',accepted:false,error:'素材引用不存在'}]}]};const before=JSON.stringify(s),r=aggregateRun(s,'r');assert.equal(r.sessionView.assembly[0].conversation.recentMessages[0].content,'真实上一轮回答');assert.equal(JSON.stringify(s),before);});
function flowRun(){return {intent:{acceptedContract:{}},stateSnapshots:[{stage:'TASK STATE',data:{id:'task',items:[{id:'one',description:'第一目标'},{id:'two',description:'第二目标'}]}}],plan:{events:[],snapshots:[]},timeline:[],contextSnapshots:[],tools:[],sessionView:{assembly:[]}};}
test('different subintents keep their own model and tool calls',()=>{const r=flowRun();r.contextSnapshots=[{callId:'m1',nodeId:'one:stage:0'},{callId:'m2',nodeId:'two'}];r.tools=[{callId:'t2',itemId:'two'}];const g=groupFlows(r);assert.equal(g.flows[0].models[0].callId,'m1');assert.equal(g.flows[1].tools[0].callId,'t2');assert.equal(g.flows[0].tools.length,0);});
test('unbound calls stay shared rather than being guessed from active task',()=>{const r=flowRun();r.contextSnapshots=[{callId:'m'}];r.tools=[{callId:'t',name:'generate_image'}];const g=groupFlows(r);assert.equal(g.shared.models.length,1);assert.equal(g.shared.tools.length,1);});
test('saved item input can bind a model call when explicit node metadata is absent',()=>{const r=flowRun();r.contextSnapshots=[{callId:'m'}];r.sessionView.assembly=[{callId:'m',components:[{item:{id:'two'}}]}];assert.equal(groupFlows(r).flows[1].models.length,1);});
