const $=id=>document.getElementById(id);
const config=await fetch('/api/config').then(r=>r.json());
let sessionId=localStorage.getItem('chorify.context-agent.session'),running=false,pending=new Map();
$('config').textContent=`独立会话 · ${config.model} · ${config.modelEnabled?'模型调用已启用':'模型调用未启用'} · ${config.mediaMode==='simulation'?'媒体模拟模式（不生成真实图片或视频）':'真实媒体需逐次批准'}`;
const post=async(path,data)=>{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','x-context-token':config.csrf},body:JSON.stringify(data)});if(!r.ok){const e=await r.json();throw new Error(e.error||'请求失败');}return r;};
function message(role,text){const node=document.createElement('article');node.className='message '+role;const label=document.createElement('div');label.className='label';label.textContent=role==='user'?'你':'Chorify';node.append(label,document.createTextNode(text));$('messages').append(node);}
function assets(items){$('assets').replaceChildren();for(const a of items){const box=document.createElement('div');box.className='asset';const label=document.createElement('p');label.textContent=(a.name||a.title||a.type)+' · v'+a.version+' · '+a.id+(a.simulated?' · 模拟产物，未实际生成':'');box.append(label);if(a.url&&!a.simulated){let u;try{u=new URL(a.url);}catch{}if(u?.protocol==='https:'){if(['image','video'].includes(a.type)){const media=document.createElement(a.type==='image'?'img':'video');media.src=a.url;if(a.type==='video')media.controls=true;else media.alt=a.name||'图片产物';box.append(media);}const link=document.createElement('a');link.href=a.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='打开原文件';box.append(link);}}if(a.content){const detail=document.createElement('details');const title=document.createElement('summary');title.textContent='查看文档';const pre=document.createElement('pre');pre.textContent=a.content;detail.append(title,pre);box.append(detail);}$('assets').append(box);}}
function proposals(){
  $('proposals').replaceChildren();if(!pending.size)return;
  const box=document.createElement('div');box.className='proposal';
  const title=document.createElement('strong');title.textContent='待批准的具体媒体调用';box.append(title);
  const newest=[...pending.values()].at(-1)?.turnId;const selected=new Set();
  for(const [id,p] of pending){
    const label=document.createElement('label'),checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.style.width='auto';checkbox.checked=p.turnId===newest;if(checkbox.checked)selected.add(id);
    checkbox.onchange=()=>{if(checkbox.checked)selected.add(id);else selected.delete(id);};
    label.append(checkbox,document.createTextNode(p.name||'媒体调用'));
    const pre=document.createElement('pre');pre.textContent=JSON.stringify(p.args||p,null,2);box.append(label,pre);
  }
  const button=document.createElement('button');button.textContent='批准选中的'+(config.mediaMode==='simulation'?'模拟':'媒体')+'调用';button.disabled=running;
  button.onclick=()=>{if(selected.size)run('/api/approve',{proposalIds:[...selected]});else $('status').textContent='请先选择具体调用。';};box.append(button);$('proposals').append(box);
}
async function refresh(){if(!sessionId)return;const r=await fetch('/api/session/'+encodeURIComponent(sessionId));if(!r.ok)throw new Error('无法读取该独立会话');const s=await r.json();$('messages').replaceChildren();for(const m of s.messages)message(m.role,m.content);assets(s.assets);pending.clear();for(const p of Object.values(s.proposals||{})){if(p.kind==='proposal'&&!Object.values(s.proposals||{}).some(a=>a.kind==='approval'&&a.proposalIds.includes(p.proposalId)))pending.set(p.proposalId,p);}proposals();}
async function newSession(){if(running)return;const s=await(await post('/api/session',{})).json();sessionId=s.id;localStorage.setItem('chorify.context-agent.session',sessionId);pending.clear();$('messages').replaceChildren();$('assets').replaceChildren();proposals();$('status').textContent='已开始独立的新对话。';}
async function run(path,data){if(running)return;running=true;$('send').disabled=true;$('new').disabled=true;proposals();$('status').textContent='正在处理…';try{const r=await post(path,{sessionId,requestId:crypto.randomUUID(),...data});const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let end;while((end=buffer.indexOf('\n'))!==-1){const line=buffer.slice(0,end);buffer=buffer.slice(end+1);if(!line.trim())continue;const e=JSON.parse(line);if(e.type==='assistant'||e.type==='assistant_progress')message('assistant',e.text);if(e.type==='tool_result'){ $('status').textContent='收到工具结果：'+e.name;const result=e.result;if(result?.proposalId&&result?.status==='approval_required')pending.set(result.proposalId,result);}if(e.type==='end')$('status').textContent=e.status==='completed'?'本轮回复结束。':e.message||e.status;}if(done)break;}await refresh();}catch(e){$('status').textContent=e.message;}finally{running=false;$('send').disabled=false;$('new').disabled=false;proposals();}}
$('chat').onsubmit=async e=>{e.preventDefault();if(running)return;try{const text=$('message').value;const inputs=[];for(const f of $('files').files){if(f.size>128*1024)throw new Error('文字文件超过 128 KiB');inputs.push({type:'text',name:f.name,content:await f.text()});}if($('image').value.trim())inputs.push({type:'image',name:'产品参考图',url:$('image').value.trim()});message('user',text);$('message').value='';$('files').value='';$('image').value='';await run('/api/chat',{message:text,inputs});}catch(error){$('status').textContent=error.message;}};
$('new').onclick=()=>newSession().catch(e=>$('status').textContent=e.message);
$('cancel').onclick=()=>post('/api/cancel',{sessionId}).then(()=>$('status').textContent='已请求停止；已提交的调用可通过回执查询。').catch(e=>$('status').textContent=e.message);
try{if(sessionId)await refresh();else await newSession();}catch{await newSession();}
