const $=id=>document.getElementById(id);
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const states={returned:'已返回',unanswered:'未见返回',failed:'失败',succeeded:'成功',not_executed:'未执行',prepared:'等待批准',pending:'处理中',unknown:'结果未知',cancelled:'已取消',completed:'运行结束',unfinished:'未记录结束',waiting_user:'等待用户',historical:'历史记录',requested:'已提出请求',ready:'输入已组装',recorded:'已记录',running:'处理中',absent:'无独立记录'};
const sectionNames={skillDirectory:'可选创作方法',assetDirectory:'本次素材目录',toolApprovals:'批准与方案',capabilities:'可用工具能力',originalMessages:'历史原话来源',historyWindow:'历史保留与裁剪',summary:'会话记忆摘要',source:'信息来源',kind:'信息类型',grantsAuthorization:'是否授予授权',system:'系统规则',user:'用户或参考资料',assistant:'Agent历史输出',function_call_output:'真实工具反馈'};
const fields={name:'名称',title:'标题',type:'类型',version:'版本',content:'正文',text:'内容',prompt:'创作描述',instruction:'修改要求',id:'对象',imageId:'目标图片',parentId:'修改原稿',parentVersion:'原稿版本',sourceIds:'来源资料',referenceImages:'参考图片',imageIds:'观察图片',sourceImageId:'原图',resultImageId:'成品',question:'观察问题',materials:'提供给观察模块的资料',slug:'创作方法',reference:'方法参考',edits:'局部修改',before:'原文',after:'替换为',size:'图片规格',duration:'时长',ratio:'比例',resolution:'分辨率',proposalIds:'选定方案',replacesProposalId:'被修订方案',proposalId:'方案',message:'反馈说明',error:'错误原因',code:'错误类别',status:'处理状态',ok:'是否成功',isError:'是否错误',submitted:'是否提交',simulated:'是否模拟',asset:'产物',assets:'产物列表',resultRefs:'结果来源',output:'返回内容',outcome:'操作结果',submission:'提交状态',requirements:'验收要求',count:'数量',unit:'计数口径',deliveryCheck:'交付检查',sourceText:'原稿正文',parentEvidence:'原稿绑定依据',changeEvidence:'修改证据',summaryText:'记忆摘要',sourceRefs:'摘要来源',characters:'字符数',total:'总数',query:'检索内容',matches:'匹配结果',records:'原文记录',note:'说明',read:'回读方式',tool:'工具',description:'用途',parameters:'参数要求',properties:'字段说明',required:'必填字段',data:'实际反馈',excerpt:'内容片段',truncated:'是否节选',complete:'是否完整',messageId:'原话来源',parentMessageId:'修改原话',sourceMessageId:'来源原话',offset:'读取起点',limit:'读取上限',maxChars:'返回字符上限',url:'素材地址'};
const internal=new Set(['call_id','callId','turnId','groupId','traceId','sourceHash','recordId','createdAt','updatedAt','ownerId','rawResultRef','traceRef','fingerprint','at','startedAt','readMore']);
let session=new URLSearchParams(location.search).get('session')||localStorage.getItem('chorify.context-agent.session'),snapshot,journey,turnId,recordId,offset=0,listEpoch=0,sessionEpoch=0,detailEpoch=0,journeyEpoch=0,refreshing=false,currentLabels={};
async function get(path){const r=await fetch(path);const data=await r.json();if(!r.ok)throw Error(data.error||'读取失败');return data;}
function friendly(value){let s=String(value??'');if(currentLabels[s])return currentLabels[s];for(const [id,label]of Object.entries(currentLabels))if(id.length>8&&s.includes(id))s=s.split(id).join('「'+label+'」');return (states[s]||s).replace(/\b[0-9a-f]{8}-[0-9a-f-]{27,}\b/gi,'（内部引用，原始证据可查）').replace(/\b[0-9a-f]{32,64}\b/gi,'（内部标识）');}
function valueView(value,depth=0){
 if(value===undefined||value===null)return el('span','未记录','muted');
 if(typeof value!=='object')return el('div',typeof value==='boolean'?(value?'是':'否'):friendly(value),'human-value');
 if(depth>7)return el('p','嵌套内容较深，请按需展开原始证据。','muted');
 if(Array.isArray(value)){const list=el('ul');if(!value.length)return el('p','无','muted');for(const item of value){const li=el('li');li.append(valueView(item,depth+1));list.append(li);}return list;}
 const dl=el('dl');for(const [key,item]of Object.entries(value)){if(internal.has(key))continue;dl.append(el('dt',fields[key]||sectionNames[key]||key));const dd=el('dd');dd.append(valueView(item,depth+1));dl.append(dd);}return dl;
}
const box=(title,data,open=false)=>{const d=el('details');d.open=open;d.append(el('summary',title),valueView(data));return d;};
function rawBox(data){const d=el('details',undefined,'evidence');d.append(el('summary','原始证据（开发者字段与内部标识）'),el('pre',JSON.stringify(data,null,2)));return d;}
function stat(label,value){const n=el('div',label,'stat');n.append(el('strong',String(value)));return n;}
async function sessions(reset=true){const epoch=++listEpoch;if(reset){offset=0;$('sessions').replaceChildren();}const query=$('search').value;const page=await get('/api/sessions?limit=20&offset='+offset+'&query='+encodeURIComponent(query));if(epoch!==listEpoch||query!==$('search').value)return;for(const s of page.sessions){const b=el('button',s.title+' · '+s.turnCount+'轮');b.dataset.session=s.id;b.classList.toggle('selected',s.id===session);b.onclick=()=>selectSession(s.id);$('sessions').append(b);}offset+=page.sessions.length;$('more').hidden=!page.hasMore;}
async function selectSession(id){session=id;sessionEpoch++;detailEpoch++;journeyEpoch++;turnId=undefined;recordId=undefined;snapshot=undefined;journey=undefined;currentLabels={};for(const id of ['timeline','turns','problems','modules','stats','overview'])$(id).replaceChildren();$('detail').replaceChildren(el('h2','处理详情'),el('p','请选择本轮问题或步骤。'));history.replaceState(null,'','/debug?session='+encodeURIComponent(id));for(const b of $('sessions').children)b.classList.toggle('selected',b.dataset.session===id);await refresh();}
function renderTurns(){ $('turns').replaceChildren();for(const [i,t]of snapshot.turns.entries()){const b=el('button',(i+1)+'. '+(typeof t.query==='string'?t.query.slice(0,65):'历史记录')+' · '+(states[t.status]||t.status));b.classList.toggle('selected',t.id===turnId);b.onclick=async()=>{turnId=t.id;recordId=undefined;detailEpoch++;$('detail').replaceChildren(el('p','选择问题或步骤查看详情。'));renderTurns();await loadJourney();};$('turns').append(b);}}
async function loadJourney(){if(!turnId)return;const epoch=++journeyEpoch,chosen=session;try{const data=await get('/api/debug/'+encodeURIComponent(chosen)+'/turn/'+encodeURIComponent(turnId));if(epoch!==journeyEpoch||chosen!==session)return;journey=data;currentLabels=data.labels;renderJourney();if(recordId)await detail(recordId);}catch(e){if(epoch===journeyEpoch)$('overview').replaceChildren(el('p',e.message));}}
function renderJourney(){
 if(!journey)return;const t=snapshot.turns.find(t=>t.id===turnId);$('overview').replaceChildren(el('h2','这一轮要完成什么'),el('p',journey.query||'旧版记录未按当前轮次格式保存。'),el('p','当前记录：'+(states[t?.status]||t?.status||'未知')+'。运行结束不代表交付已经合格。','muted'));
 $('stats').replaceChildren(stat('本轮 Agent 决策',journey.decisions),stat('工具请求',t?.tools.length||0),stat('错误 / 待处理',journey.issues.filter(i=>i.severity==='error').length+' / '+journey.issues.filter(i=>i.severity==='warning').length),stat('待核查信号',journey.issues.filter(i=>i.severity==='signal').length));
 $('problems').replaceChildren(el('h2','先看哪里出了问题'));if(!journey.issues.length)$('problems').append(el('p','记录中未发现可直接识别的执行异常；素材选择、事实和创作范围是否正确仍需核查。','empty'));else{const list=el('div',undefined,'problem-list');for(const issue of journey.issues){const b=el('button',undefined,'problem '+(issue.severity==='signal'?'signal':''));b.append(el('strong',(issue.severity==='signal'?'待核查 · ':issue.severity==='warning'?'待处理 · ':'异常 · ')+issue.title),el('div',issue.description));if(issue.followUp)b.append(el('div',issue.followUp,'followup'));b.onclick=()=>detail(issue.nodeId);list.append(b);}$('problems').append(list);}
 $('modules').replaceChildren();for(const m of journey.modules){const b=el('button',undefined,'module '+m.status);b.append(el('strong',m.title),el('span',states[m.status]||m.status),el('span',m.summary,'muted'));b.disabled=!m.nodeId;b.onclick=()=>detail(m.nodeId);$('modules').append(b);}timeline();
}
function timeline(){ $('timeline').replaceChildren();if(!journey)return;const mode=$('filter').value;let visible=journey.nodes;if(mode==='problems'){const ids=new Set(journey.issues.flatMap(i=>[i.nodeId,i.nextId]));visible=visible.filter(n=>ids.has(n.id));}else if(mode!=='all')visible=visible.filter(n=>mode==='execution'?['system','execution','feedback'].includes(n.module):n.module===mode);
 for(const [i,node]of visible.entries()){const wrap=el('div',undefined,'step'),b=el('button',undefined,node.module+' '+node.status);b.classList.toggle('selected',node.id===recordId);b.append(el('strong',node.title),el('span',states[node.status]||node.status,'tag'),el('span',node.at?.slice(11,19)||'','muted'),el('div',node.summary.length>200?node.summary.slice(0,200)+'…':node.summary,'summary-text'));if(node.incomingProblems?.length)b.append(el('div',node.incomingProblems.map(p=>(p.delivered?'已收到：':'未找到直接反馈：')+p.title).join('；'),'summary-text'));b.onclick=()=>detail(node.id);wrap.append(b);$('timeline').append(wrap);}if(!visible.length)$('timeline').append(el('p','当前筛选没有对应记录。','empty'));
}
function imagePreview(block){const v=block.data;if(!v||typeof v!=='object')return null;const url=v.image_url?.url||v.image_url||v.url;if(!['input_image','image_url'].includes(v.type)||typeof url!=='string'||!/^https:\/\//.test(url))return null;const button=el('button','加载该次请求引用的图片');button.onclick=()=>{const img=el('img');img.alt='该次模型输入引用的图片';img.className='image-ref';img.referrerPolicy='no-referrer';img.src=url;img.onerror=()=>{button.textContent='原图片无法加载';};button.after(img);button.disabled=true;};return button;}
function linkButton(title,id){const b=el('button',title,'source');b.onclick=()=>detail(id);return b;}
function showContext(root,data){root.append(el('h3','这次决策实际收到了什么'));const m=data.record.metrics;if(m){const dl={保留记录:m.retainedRecords,未进入输入的历史记录:m.omittedRecords,输入估算token:m.estimatedInputTokens,工具定义估算token:m.estimatedToolDefinitionTokens,上下文预算:m.tokenBudget};root.append(box('输入规模与裁剪',dl,true));}if(data.response?.usage)root.append(box('供应商返回的用量',data.response.usage));
 for(const b of data.blocks){if(['source','kind','grantsAuthorization','服务端数据来源说明','originalMessages'].includes(b.name))continue;const d=box('输入 '+(b.index+1)+' · '+(sectionNames[b.role]||b.role)+' · '+(sectionNames[b.name]||b.name),b.data);const preview=imagePreview(b);if(preview)d.append(preview);root.append(d);}
 if(data.sources?.length){const d=el('details');d.append(el('summary','查阅本次保留的原始来源（'+data.sources.length+'）'),el('p','这里回读持久原文；实际发送的节选与投影请以上方输入为准。','muted'));for(const source of data.sources)d.append(linkButton(source.label,source.id));root.append(d);}
 if(data.references?.length)root.append(box('输入包含的素材（出现不等于已读取）',data.references));const defs=el('details');defs.append(el('summary','Agent 当时可选的工具（'+data.tools.length+'）'));for(const tool of data.tools)defs.append(box(tool.description||tool.name,tool.parameters||tool));root.append(defs);
}
async function detail(id){recordId=id;const epoch=++detailEpoch,chosen=session;$('detail').replaceChildren(el('p','读取原始记录…'));timeline();try{const target=journey?.nodes.find(n=>n.id===id)?.recordId||id;const data=await get('/api/debug/'+encodeURIComponent(chosen)+'/record/'+encodeURIComponent(target));if(epoch!==detailEpoch||chosen!==session)return;currentLabels={...currentLabels,...data.labels};const root=$('detail'),node=journey?.nodes.find(n=>n.id===id);root.replaceChildren(el('h2',node?.title||data.title||'来源详情'));if(node)root.append(el('p',node.summary));const issue=journey?.issues.find(i=>i.nodeId===id);if(issue){root.append(el('p',issue.description,'notice'));if(issue.followUp)root.append(el('p',issue.followUp,issue.feedbackDelivered?'success-note':'notice'));if(issue.nextId)root.append(linkButton('查看之后 Agent 如何决定',issue.nextId));}
 if(node?.incomingProblems?.length){root.append(el('h3','此前反馈有没有进入输入'));for(const p of node.incomingProblems)root.append(linkButton((p.delivered?'已送达 · ':'未找到直接反馈 · ')+p.title,p.nodeId));root.append(el('p','送达只证明模型有机会看到，不证明它理解或纠正了问题。','muted'));}
 if(data.blocks){const output=Array.isArray(data.response?.output)?data.response.output:[];root.append(el('h3','Agent 返回了什么'));const text=output.filter(p=>p.type==='message').map(p=>typeof p.content==='string'?p.content:(p.content||[]).map(v=>v.text||'').join('\n')).join('\n');if(text)root.append(valueView(text));const choices=output.filter(p=>p.type==='function_call');for(const c of choices){let args;try{args=JSON.parse(c.arguments);}catch{args=c.arguments;}root.append(box('提出的工具请求：'+(journey?.nodes.find(n=>n.callId===c.call_id&&n.tool)?.title?.replace('Agent 申请','')||node?.choices?.find(x=>x.name===c.name)?.label||c.name),args,true));}if(!data.response)root.append(el('p','尚无返回证据。','notice'));if(data.response?.event==='model_error')root.append(el('p',friendly(data.response.message),'notice'));showContext(root,data);}
 else if(data.record.kind==='tool_call'){root.append(box('Agent 交给工具的内容',data.arguments,true));if(data.result){let result;try{result=JSON.parse(data.result.output);}catch{result=data.result.output;}root.append(box('系统或工具实际返回',result,true));}else root.append(el('p','尚无工具结果。','notice'));const item=snapshot?.turns.flatMap(t=>t.tools).find(c=>c.id===id),m=snapshot?.turns.flatMap(t=>t.models).find(m=>m.traceId===item?.agentTraceId);if(m)root.append(linkButton('回看 Agent 为什么提出这次调用（查看实际输入与输出）',m.id));}
 else if(node?.coverage){root.append(box('本次整理涉及的用户原话',node.coverage.map(c=>c.label),true));if(node.savedSummary)root.append(box('实际保存的记忆摘要',node.savedSummary,true));}
 else if(data.record.kind==='message')root.append(valueView(data.record.content));
 else if(data.record.kind==='tool_result'){root.append(box('返回的具体内容',data.output,true));if(node?.requestId)root.append(linkButton('回看这次工具请求',node.requestId));}
 else if(data.record.event==='summary_failed')root.append(valueView(data.record.message));
 else if(data.record.event==='tool_batch_policy'){root.append(el('p',data.record.rule||'当时没有记录执行规则。'));root.append(el('p','这是固定执行规则，不是对语义依赖的模型审查。','muted'));}
 else if(data.output)root.append(box('系统反馈内容',data.output,true));
 else if(data.record.event==='end')root.append(box('运行结束情况',{status:data.record.result?.status,message:data.record.result?.message,模型请求次数:data.record.result?.modelCalls,工具选择次数:data.record.result?.toolCalls},true));
 else if(!node)root.append(el('p','这类历史事件没有专用解释，可展开下方原始证据。','muted'));
 root.append(el('p','阅读视图将内部标识显示为名称；原始证据中的输入与输出保持原样。','muted'),rawBox(data));
 }catch(e){if(epoch===detailEpoch)$('detail').replaceChildren(el('p',e.message,'notice'));}}
async function refresh(){if(!session){$('status').textContent='请选择一个已有会话。';return;}if(refreshing)return;refreshing=true;const chosen=session,epoch=sessionEpoch;try{const data=await get('/api/debug/'+encodeURIComponent(chosen));if(chosen!==session||epoch!==sessionEpoch)return;const changed=snapshot?.recordCount!==data.recordCount;snapshot=data;if(!turnId||!data.turns.some(t=>t.id===turnId))turnId=data.turns.at(-1)?.id;$('status').textContent=(data.running?'会话运行中':'会话未在运行')+' · '+new Date().toLocaleTimeString()+' · 显示已记录事实，不自动判定语义正确';$('export').href='/api/session/'+encodeURIComponent(session)+'/export';renderTurns();if(changed)await loadJourney();}catch(e){if(chosen===session)$('status').textContent=e.message;}finally{refreshing=false;if(chosen!==session)refresh();}}
$('search-form').onsubmit=e=>{e.preventDefault();sessions().catch(e=>$('status').textContent=e.message);};$('more').onclick=()=>sessions(false).catch(e=>$('status').textContent=e.message);$('refresh').onclick=()=>refresh();$('filter').onchange=timeline;
await sessions().catch(e=>$('status').textContent=e.message);await refresh();setInterval(()=>{if($('auto').checked&&!document.hidden)refresh();},3000);
