const $=id=>document.getElementById(id);
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const json=value=>typeof value==='string'?value:JSON.stringify(value,null,2);
const phases={agent:'主 Agent',summary:'记忆摘要',image_observation:'视觉观察'};
const sectionNames={skillDirectory:'Skill 方法索引',assetDirectory:'素材目录',toolApprovals:'工具批准',capabilities:'当前能力',originalMessages:'原始消息身份索引',historyWindow:'历史窗口与遗漏',summary:'会话摘要',source:'来源',kind:'数据类型',grantsAuthorization:'是否授予授权'};
const states={returned:'已返回',unanswered:'未见返回',failed:'失败',succeeded:'成功',not_executed:'未执行',prepared:'待批准',pending:'处理中',unknown:'未知',cancelled:'取消',completed:'运行结束',unfinished:'未记录结束',waiting_user:'等待用户',historical:'历史记录'};
let session=new URLSearchParams(location.search).get('session')||localStorage.getItem('chorify.context-agent.session'),snapshot,turnId,recordId,offset=0,listEpoch=0,sessionEpoch=0,detailEpoch=0,refreshing=false;
async function get(path){const r=await fetch(path);const data=await r.json();if(!r.ok)throw Error(data.error||'读取失败');return data;}
const box=(title,data,open=false)=>{const d=el('details');d.open=open;d.append(el('summary',title),el('pre',json(data)));return d;};
function stat(label,value){const n=el('div',label,'stat');n.append(el('strong',String(value)));return n;}
async function sessions(reset=true){const epoch=++listEpoch;if(reset){offset=0;$('sessions').replaceChildren();}const query=$('search').value;const page=await get('/api/sessions?limit=20&offset='+offset+'&query='+encodeURIComponent(query));if(epoch!==listEpoch||query!==$('search').value)return;for(const s of page.sessions){const b=el('button',s.title+' · '+s.turnCount+'轮');b.dataset.session=s.id;b.classList.toggle('selected',s.id===session);b.onclick=()=>selectSession(s.id);$('sessions').append(b);}offset+=page.sessions.length;$('more').hidden=!page.hasMore;}
async function selectSession(id){session=id;sessionEpoch++;detailEpoch++;turnId=undefined;recordId=undefined;snapshot=undefined;$('timeline').replaceChildren();$('turns').replaceChildren();$('detail').replaceChildren(el('h2','调用详情'),el('p','请选择一个节点。'));history.replaceState(null,'','/debug?session='+encodeURIComponent(id));for(const b of $('sessions').children)b.classList.toggle('selected',b.dataset.session===id);await refresh();}
function render(){const c=snapshot.counts;$('stats').replaceChildren(stat('主 Agent 调用',c.phases.agent||0),stat('摘要调用',c.phases.summary||0),stat('视觉调用',c.phases.image_observation||0),stat('工具选择',c.tools),stat('工具失败 / 未执行',c.failedTools+' / '+c.deferredTools));$('turns').replaceChildren();for(const [i,t]of snapshot.turns.entries()){const b=el('button',(i+1)+'. '+(typeof t.query==='string'?t.query.slice(0,65):'历史记录')+' · '+(states[t.status]||t.status));b.classList.toggle('selected',t.id===turnId);b.onclick=()=>{turnId=t.id;recordId=undefined;detailEpoch++;$('detail').replaceChildren(el('h2','调用详情'),el('p','请选择本轮节点。'));render();};$('turns').append(b);}timeline();}
function timeline(){const t=snapshot?.turns.find(t=>t.id===turnId);$('timeline').replaceChildren();if(!t)return;const items=[...t.models.map(m=>({...m,category:'model',title:(phases[m.phase]||m.phase)+' · '+(states[m.status]||m.status)})),...t.tools.map(c=>({...c,category:'tool',title:c.name+' · '+(states[c.status]||c.status)})),...t.events.map(e=>({...e,category:'event',title:e.name||e.event}))].sort((a,b)=>a.seq-b.seq);$('timeline').append(box('本轮用户输入',t.query),box('本轮调用统计',{models:t.models.length,agent:t.models.filter(m=>m.phase==='agent').length,tools:t.tools.length,accounting:t.accounting||'尚无结束统计；上方按实际请求记录计数'}));for(const item of items){if($('filter').value!=='all'&&item.category!==$('filter').value)continue;const b=el('button',item.title,'node '+item.category+(item.status==='failed'?' failed':''));b.classList.toggle('selected',recordId===item.id);b.append(el('div',[item.at?.slice(11,23),item.durationMs!==undefined?item.durationMs+' ms':'',item.callId?'call '+item.callId.slice(0,12):''].filter(Boolean).join(' · '),'muted'));b.onclick=()=>detail(item.id);$('timeline').append(b);}if(!items.length)$('timeline').append(el('p','此轮没有当前执行内核的模型或工具记录。'));}
function imagePreview(block){const v=block.data;if(!v||typeof v!=='object')return null;const url=v.image_url?.url||v.image_url||v.url;if(!['input_image','image_url'].includes(v.type)||typeof url!=='string'||!/^https:\/\//.test(url))return null;const button=el('button','加载实际引用图片（访问原始地址）');button.onclick=()=>{const img=el('img');img.alt='该次模型输入引用的图片';img.className='image-ref';img.referrerPolicy='no-referrer';img.src=url;img.onerror=()=>{button.textContent='原图片无法加载';};button.after(img);button.disabled=true;};return button;}
async function detail(id){recordId=id;const epoch=++detailEpoch,chosen=session;$('detail').replaceChildren(el('p','读取原始记录…'));timeline();try{const data=await get('/api/debug/'+encodeURIComponent(chosen)+'/record/'+encodeURIComponent(id));if(epoch!==detailEpoch||chosen!==session)return;const root=$('detail');root.replaceChildren(el('h2',data.record.event||data.record.name||data.record.kind),el('p','记录 '+id,'muted'));
 if(data.blocks){root.append(el('p',data.note,'notice'));root.append(box('预算、裁剪与用量',{metrics:data.record.metrics||'未记录',usage:data.response?.usage||'未记录'},true));root.append(el('h3','模型输入 · 原始顺序'));for(const b of data.blocks){const d=box('#'+(b.index+1)+' · '+b.role+' · '+(sectionNames[b.name]||b.name)+(b.callId?' · '+b.callId:''),b.data);const preview=imagePreview(b);if(preview)d.append(preview);root.append(d);}const ids=data.record.metrics?.retainedRecordIds||[];if(ids.length){const refs=el('details');refs.append(el('summary','输入保留的来源记录（'+ids.length+'）'));for(const rid of ids){const b=el('button',rid);b.onclick=()=>detail(rid);refs.append(b);}root.append(refs);}const defs=el('details');defs.append(el('summary','本次工具定义（'+data.tools.length+'）'));for(const tool of data.tools)defs.append(box(tool.name||tool.function?.name||'工具',tool));root.append(defs);root.append(box('输入中出现的素材 ID（不代表已经读取或被采纳）',data.references));root.append(el('h3','Agent / 模型输出'));root.append(box('完整输出或错误',data.response||'尚无持久返回；可能仍在运行或已中断',true));}
 else if(data.record.kind==='tool_call'){root.append(box('工具输入',data.arguments,true));root.append(box('工具输出',data.result?(()=>{try{return JSON.parse(data.result.output);}catch{return data.result.output;}})():'尚未记录结果',true));const item=snapshot.turns.flatMap(t=>t.tools).find(c=>c.id===id);if(item?.agentTraceId){const model=snapshot.turns.flatMap(t=>t.models).find(m=>m.traceId===item.agentTraceId);if(model){const b=el('button','查看选择此工具的 Agent 调用');b.onclick=()=>detail(model.id);root.append(b);}}}
 else root.append(box('系统记录与判断依据',data.output??data.record,true));root.append(box('完整原始记录',data));
 }catch(e){if(epoch===detailEpoch)$('detail').replaceChildren(el('p',e.message,'notice'));}}
async function refresh(){if(!session){$('status').textContent='请选择一个已有会话。';return;}if(refreshing)return;refreshing=true;const chosen=session,epoch=sessionEpoch;try{const data=await get('/api/debug/'+encodeURIComponent(chosen));if(chosen!==session||epoch!==sessionEpoch)return;const changed=snapshot?.recordCount!==data.recordCount;snapshot=data;if(!turnId||!data.turns.some(t=>t.id===turnId))turnId=data.turns.at(-1)?.id;$('status').textContent=(data.running?'会话运行中':'会话未在运行')+' · '+data.recordCount+'条记录 · '+new Date().toLocaleTimeString()+(data.legacy?' · 旧格式完整记录请使用导出查看':'');$('export').href='/api/session/'+encodeURIComponent(session)+'/export';if(changed)render();if(changed&&recordId)await detail(recordId);}catch(e){if(chosen===session)$('status').textContent=e.message;}finally{refreshing=false;if(chosen!==session)refresh();}}
$('search-form').onsubmit=e=>{e.preventDefault();sessions().catch(e=>$('status').textContent=e.message);};$('more').onclick=()=>sessions(false).catch(e=>$('status').textContent=e.message);$('refresh').onclick=()=>refresh();$('filter').onchange=timeline;
await sessions().catch(e=>$('status').textContent=e.message);await refresh();setInterval(()=>{if($('auto').checked&&!document.hidden)refresh();},3000);
